CREATE TABLE posts(
postID BIGINT( 15 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
postTitle VARCHAR( 250 ) ,
postHead TEXT NOT NULL ,
postBody TEXT,
authorID INT( 12 ) REFERENCES users( userID ) ON DELETE CASCADE ,
postCreateTime TIMESTAMP NOT NULL ,
postModifyTime TIMESTAMP,
active TINYINT(1)
)