CREATE TABLE postTags (
	postID BIGINT(15) NOT NULL ,
	tagID INT(12) NOT NULL ,

	CONSTRAINT postTag PRIMARY KEY (postID,tagID),
	FOREIGN KEY (postID) REFERENCES posts(postID) ON DELETE CASCADE,
	FOREIGN KEY (tagID) REFERENCES tags(tagID) ON DELETE CASCADE

);
