CREATE TABLE postTags (
	postID BIGINT(15) NOT NULL REFERENCES posts(postID) ON DELETE CASCADE,
	tagID INT(12) NOT NULL REFERENCES tags(tagID) ON DELETE CASCADE,

	CONSTRAINT postTag PRIMARY KEY (postID,tagID)
);
